Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
path = "./sf-model-lib/diffusion"
path_train = os.path.join(path, 'g_train_original.hdf5')
path_weights = os.path.join(path, 'model_weights.h5')
g_train = h5py.File(path_train, 'r')['g_train'][()]
model = ps.networks.create_model()
model.load_weights(path_weights)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[4], line 5[0m
[1;32m      3[0m path_weights [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin(path, [38;5;124m'[39m[38;5;124mmodel_weights.h5[39m[38;5;124m'[39m)
[1;32m      4[0m g_train [38;5;241m=[39m h5py[38;5;241m.[39mFile(path_train, [38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m)[[38;5;124m'[39m[38;5;124mg_train[39m[38;5;124m'[39m][()]
[0;32m----> 5[0m model [38;5;241m=[39m [43mps[49m[38;5;241;43m.[39;49m[43mnetworks[49m[38;5;241;43m.[39;49m[43mcreate_model[49m[43m([49m[43m)[49m
[1;32m      6[0m model[38;5;241m.[39mload_weights(path_weights)

File [0;32m~/work/porespy/porespy/porespy/networks/_size_factors.py:612[0m, in [0;36mcreate_model[0;34m()[0m
[1;32m    604[0m [38;5;28;01mdef[39;00m [38;5;21mcreate_model[39m():
[1;32m    605[0m [38;5;250m    [39m[38;5;124;03m'''[39;00m
[1;32m    606[0m [38;5;124;03m    Returns[39;00m
[1;32m    607[0m [38;5;124;03m    -------[39;00m
[0;32m   (...)[0m
[1;32m    610[0m 
[1;32m    611[0m [38;5;124;03m    '''[39;00m
[0;32m--> 612[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mtensorflow[39;00m[38;5;21;01m.[39;00m[38;5;21;01mkeras[39;00m[38;5;21;01m.[39;00m[38;5;21;01moptimizers[39;00m [38;5;28;01mimport[39;00m Adam
[1;32m    613[0m     model [38;5;241m=[39m _resnet3d()
[1;32m    614[0m     model[38;5;241m.[39mcompile(loss[38;5;241m=[39m[38;5;124m'[39m[38;5;124mmse[39m[38;5;124m'[39m, optimizer[38;5;241m=[39mAdam(lr[38;5;241m=[39m[38;5;241m1e-4[39m), metrics[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mmse[39m[38;5;124m'[39m])

File [0;32m/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/tensorflow/__init__.py:38[0m
[1;32m     35[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m [38;5;28;01mas[39;00m [38;5;21;01m_sys[39;00m
[1;32m     36[0m [38;5;28;01mimport[39;00m [38;5;21;01mtyping[39;00m [38;5;28;01mas[39;00m [38;5;21;01m_typing[39;00m
[0;32m---> 38[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtensorflow[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtools[39;00m [38;5;28;01mimport[39;00m module_util [38;5;28;01mas[39;00m _module_util
[1;32m     39[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtensorflow[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutil[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlazy_loader[39;00m [38;5;28;01mimport[39;00m LazyLoader [38;5;28;01mas[39;00m _LazyLoader
[1;32m     41[0m [38;5;66;03m# Make sure code inside the TensorFlow codebase can use tf2.enabled() at import.[39;00m

[0;31mModuleNotFoundError[0m: No module named 'tensorflow.python'

